import React, { useState } from 'react';

const CreateMarketForm = () => {
  const [advancedOptions, setAdvancedOptions] = useState(false);

  return (
    <div className="container mx-auto p-6">
      {/* Info box */}
      <div className="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mb-6 rounded-md">
        <p>
          <strong>When creating an OpenBook ID</strong>, you need to complete two signing actions: first generate the market information, then you can create the market. The second signing utilizes the information generated by the first, thus the execution process may be affected by local network conditions. If the operation continues to fail, consider switching to a more stable network connection or enabling the global mode of a VPN before attempting the operation again.
        </p>
      </div>

      {/* Form fields */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
        {/* Base Token */}
        <div>
          <label className="font-bold mb-1 block">Base Token:</label>
          <input
            type="text"
            placeholder="Select Base Token"
            className="border border-gray-300 rounded-lg w-full p-2"
          />
          <p className="text-blue-500 text-sm mt-1">Can't find the currency? <a href="#" className="underline">Try customizing.</a></p>
        </div>

        {/* Quote Token */}
        <div>
          <label className="font-bold mb-1 block">Quote Token:</label>
          <input
            type="text"
            placeholder="Select Quote Token"
            className="border border-gray-300 rounded-lg w-full p-2"
          />
          <p className="text-blue-500 text-sm mt-1">Can't find the currency? <a href="#" className="underline">Try customizing.</a></p>
        </div>

        {/* Min Order Size */}
        <div>
          <label className="font-bold mb-1 block">Min Order Size:</label>
          <div className="flex">
            <button className="bg-gray-200 py-2 px-3 rounded-l-lg">-</button>
            <input
              type="number"
              className="border border-gray-300 text-center w-full p-2"
              value="1"
            />
            <button className="bg-gray-200 py-2 px-3 rounded-r-lg">+</button>
          </div>
        </div>

        {/* Price Increment */}
        <div>
          <label className="font-bold mb-1 block">Price Increment:</label>
          <div className="flex">
            <button className="bg-gray-200 py-2 px-3 rounded-l-lg">-</button>
            <input
              type="number"
              className="border border-gray-300 text-center w-full p-2"
              value="0.000001"
            />
            <button className="bg-gray-200 py-2 px-3 rounded-r-lg">+</button>
          </div>
        </div>
      </div>

      {/* Advanced Options Toggle */}
      <div className="mb-6">
        <button
          onClick={() => setAdvancedOptions(!advancedOptions)}
          className="text-orange-500 font-bold"
        >
          Advanced Options {advancedOptions ? '▲' : '▼'}
        </button>
      </div>

      {/* Advanced Options */}
      {advancedOptions && (
        <div className="bg-gray-100 p-6 rounded-lg mb-6">
          <h3 className="font-bold mb-4">Configuration</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {/* SOL Configurations */}
            <div>
              <div className="flex space-x-4">
                <button className="bg-gray-200 py-2 px-4 rounded-lg">0.29 SOL</button>
                <button className="bg-gray-200 py-2 px-4 rounded-lg">1.4 SOL</button>
                <button className="bg-gray-200 py-2 px-4 rounded-lg">2.7 SOL</button>
              </div>
            </div>

            {/* Event Queue Length */}
            <div>
              <label className="font-bold mb-1 block">Event Queue Length:</label>
              <div className="flex">
                <button className="bg-gray-200 py-2 px-3 rounded-l-lg">-</button>
                <input
                  type="number"
                  className="border border-gray-300 text-center w-full p-2"
                  value="128"
                />
                <button className="bg-gray-200 py-2 px-3 rounded-r-lg">+</button>
              </div>
              <p className="text-sm text-gray-500">11308 Bytes</p>
            </div>

            {/* Request Queue Length */}
            <div>
              <label className="font-bold mb-1 block">Request Queue Length:</label>
              <div className="flex">
                <button className="bg-gray-200 py-2 px-3 rounded-l-lg">-</button>
                <input
                  type="number"
                  className="border border-gray-300 text-center w-full p-2"
                  value="9"
                />
                <button className="bg-gray-200 py-2 px-3 rounded-r-lg">+</button>
              </div>
              <p className="text-sm text-gray-500">764 Bytes</p>
            </div>

            {/* Orderbook Length */}
            <div>
              <label className="font-bold mb-1 block">Orderbook Length:</label>
              <div className="flex">
                <button className="bg-gray-200 py-2 px-3 rounded-l-lg">-</button>
                <input
                  type="number"
                  className="border border-gray-300 text-center w-full p-2"
                  value="201"
                />
                <button className="bg-gray-200 py-2 px-3 rounded-r-lg">+</button>
              </div>
              <p className="text-sm text-gray-500">14524 Bytes</p>
            </div>
          </div>
        </div>
      )}

      {/* Submit button */}
      <button className="bg-orange-500 text-white py-2 px-6 rounded-lg mt-4">
        Create Market
      </button>
      <p className="text-sm text-gray-400 mt-2">The lowest service fee on the entire network is 0.1 SOL.</p>
    </div>
  );
};

export default CreateMarketForm;
